import type { SectionDefinition } from "../types/proposalForm";

const sectionRegistry: Record<string, SectionDefinition> = {
  dados_proposta: {
    id: "dados_proposta",
    title: "Dados da proposta",
    required: true,
    fields: ["numero_proposta", "data_solicitacao", "data_envio"],
    layout: {
      numero_proposta: { span: "full" },
    },
  },
  dados_cliente: {
    id: "dados_cliente",
    title: "Dados do cliente",
    required: true,
    fields: [
      "nome_razao_social",
      "cpf_cnpj",
      "nome_contato",
      "telefone",
      "email",
    ],
  },
  dados_obra: {
    id: "dados_obra",
    title: "Dados da obra",
    required: true,
    fields: ["endereco_cliente", "nome_da_obra", "local_obra", "cidade", "estado", "tipo_projeto"],
  },
  produto_variante: {
    id: "produto_variante",
    title: "Produto e variante",
    fields: ["variante_quadra_tenis"],
  },
  produto_variante_quadra_poliesportiva: {
    id: "produto_variante_quadra_poliesportiva",
    title: "Produto e variante",
    fields: ["variante_quadra_poliesportiva"],
  },
  produto_variante_beach_tenis: {
    id: "produto_variante_beach_tenis",
    title: "Produto e variante",
    fields: ["variante_beach_tenis"],
  },
  produto_variante_campo: {
    id: "produto_variante_campo",
    title: "Produto e variante",
    fields: ["variante_campo"],
  },
  produto_variante_pickleball: {
    id: "produto_variante_pickleball",
    title: "Produto e variante",
    fields: ["variante_pickleball"],
  },
  produto_variante_padel: {
    id: "produto_variante_padel",
    title: "Produto e variante",
    fields: ["variante_padel"],
  },
  produto_variante_squash: {
    id: "produto_variante_squash",
    title: "Produto e variante",
    fields: ["variante_squash"],
  },
  produto_variante_pista: {
    id: "produto_variante_pista",
    title: "Produto e variante",
    fields: ["variante_pista"],
  },
  produto_variante_garagem_epoxi: {
    id: "produto_variante_garagem_epoxi",
    title: "Produto e variante",
    fields: ["variante_garagem_epoxi"],
  },
  produto_variante_softplay: {
    id: "produto_variante_softplay",
    title: "Produto e variante",
    fields: ["variante_softplay"],
  },
  dimensoes: {
    id: "dimensoes",
    title: "Dimensões",
    description: "Informe largura, comprimento e área total da quadra.",
    fields: ["largura", "comprimento", "area_total"],
    layout: {
      largura: { span: 1 },
      comprimento: { span: 1 },
      area_total: { span: "full" },
    },
  },
  condicoes_obra: {
    id: "condicoes_obra",
    title: "Condições da obra",
    fields: [
      "tipo_terreno",
      "dificuldade_acesso",
      "responsavel_material_pedreira",
    ],
  },
  especificacoes_variante: {
    id: "especificacoes_variante",
    title: "Especificações",
    fields: [
      "cor_piso_asfaltico",
      "especificar_cor",
      "possui_playcushion",
      "possui_kit_saibro",
    ],
    layout: {
      especificar_cor: { span: "full" },
    },
  },
  especificacoes_variante_quadra_poliesportiva: {
    id: "especificacoes_variante_quadra_poliesportiva",
    title: "Especificações da variante",
    fields: [
      "tipo_madeira",
      "anti_chama",
      "condicao_base_piso",
      "tipo_poliuretano",
    ],
  },
  especificacoes_beach_tenis: {
    id: "especificacoes_beach_tenis",
    title: "Especificações do Beach Tennis",
    fields: ["tipo_areia", "espessura_areia", "possui_eva"],
    layout: {
      possui_eva: { span: "full" },
    },
  },
  especificacoes_softplay: {
    id: "especificacoes_softplay",
    title: "Especificações do Softplay",
    fields: ["espessura_sbr", "espessura_epdm", "tipo_epdm"],
  },
  especificacoes_variante_campo: {
    id: "especificacoes_variante_campo",
    title: "Especificações da variante",
    fields: [
      "tipo_grama_natural",
      "especificar_tipo_grama_natural",
      "tipo_grama_sintetica",
      "especificar_tipo_grama_sintetica",
      "altura_grama_sintetica",
      "base_drenante",
      "possui_shockpad",
    ],
    layout: {
      especificar_tipo_grama_natural: { span: "full" },
      especificar_tipo_grama_sintetica: { span: "full" },
      possui_shockpad: { span: "full" },
    },
  },
  especificacoes_pickleball: {
    id: "especificacoes_pickleball",
    title: "Especificações do Pickleball",
    fields: ["cor_pickleball", "especificar_cor_pickleball"],
    layout: {
      especificar_cor_pickleball: { span: "full" },
    },
  },
  especificacoes_padel: {
    id: "especificacoes_padel",
    title: "Especificações do Padel",
    fields: ["tipo_grama_padel"],
  },
  especificacoes_squash: {
    id: "especificacoes_squash",
    title: "Especificações do Squash",
    fields: ["tipo_madeira", "anti_chama"],
    layout: {
      anti_chama: { span: "full" },
    },
  },
  especificacoes_pista: {
    id: "especificacoes_pista",
    title: "Especificações da pista",
    fields: ["numero_raias", "opcao_pu_200_b_pista"],
  },
  dimensoes_garagem_epoxi: {
    id: "dimensoes_garagem_epoxi",
    title: "Dimensões da garagem",
    fields: [
      "largura_piso_liso",
      "comprimento_piso_liso",
      "area_piso_liso",
      "largura_piso_derrapante",
      "comprimento_piso_derrapante",
      "area_piso_derrapante",
    ],
    layout: {
      area_piso_liso: { span: "full" },
      area_piso_derrapante: { span: "full" },
    },
  },
  especificacoes_garagem_epoxi: {
    id: "especificacoes_garagem_epoxi",
    title: "Especificações da garagem epóxi",
    fields: [
      "possui_multilayer_garagem_epoxi",
      "condicao_base_piso_garagem_epoxi",
      "metro_linear_faixa",
    ],
    layout: {
      possui_multilayer_garagem_epoxi: { span: "full" },
    },
  },
  vagas_garagem_epoxi: {
    id: "vagas_garagem_epoxi",
    title: "Vagas",
    fields: [
      "possui_vagas_carro",
      "quantidade_vagas_carro",
      "largura_vaga_carro",
      "comprimento_vaga_carro",
      "possui_vagas_moto",
      "quantidade_vagas_moto",
      "largura_vaga_moto",
      "comprimento_vaga_moto",
      "possui_vagas_bicicleta",
      "quantidade_vagas_bicicleta",
      "largura_vaga_bicicleta",
      "comprimento_vaga_bicicleta",
      "possui_vagas_pne",
      "quantidade_vagas_pne",
      "largura_vaga_pne",
      "comprimento_vaga_pne",
    ],
    layout: {
      possui_vagas_carro: { span: "full" },
      quantidade_vagas_carro: { span: "full" },
      possui_vagas_moto: { span: "full" },
      quantidade_vagas_moto: { span: "full" },
      possui_vagas_bicicleta: { span: "full" },
      quantidade_vagas_bicicleta: { span: "full" },
      possui_vagas_pne: { span: "full" },
      quantidade_vagas_pne: { span: "full" },
    },
  },
  iluminacao: {
    id: "iluminacao",
    title: "Iluminação",
    fields: [
      "possui_iluminacao",
      "iluminacao_fixada_alambrado",
      "quantidade_postes_iluminacao",
      "altura_postes_iluminacao",
      "quantidade_projetores",
      "potencia_projetores",
      "especificar_potencia_projetores",
      "quantidade_cruzetas",
      "cor_cruzetas",
      "responsavel_ligacao_eletrica",
      "tipo_coligacao",
    ],
    groups: [
      {
        id: "campos_iluminacao",
        title: "Dados da iluminação",
        triggerField: "possui_iluminacao",
        fields: [
          "iluminacao_fixada_alambrado",
          "quantidade_postes_iluminacao",
          "altura_postes_iluminacao",
          "quantidade_projetores",
          "potencia_projetores",
          "especificar_potencia_projetores",
          "quantidade_cruzetas",
          "cor_cruzetas",
          "responsavel_ligacao_eletrica",
          "tipo_coligacao",
        ],
      },
    ],
    layout: {
      possui_iluminacao: { span: "full" },
      iluminacao_fixada_alambrado: { span: "full" },
      especificar_potencia_projetores: { span: "full" },
    },
  },
  fechamentos_protecoes: {
    id: "fechamentos_protecoes",
    title: "Fechamentos e proteções",
    description: "Inclui alambrado, tela superior e tela de sombreamento.",
    fields: [
      "possui_alambrado",
      "sistema_alambrado",
      "galvanizacao",
      "especificar_galvanizacao",
      "cor_tela_alambrado",
      "cor_tubo_alambrado",
      "cor_tela_malha_alambrado",
      "comprimento_alambrado_laterais",
      "altura_alambrado_laterais",
      "espacamento_postes_tubos_laterais",
      "comprimento_alambrado_lateral_1",
      "altura_alambrado_lateral_1",
      "espacamento_postes_tubos_lateral_1",
      "comprimento_alambrado_lateral_2",
      "altura_alambrado_lateral_2",
      "espacamento_postes_tubos_lateral_2",
      "comprimento_alambrado_fundos",
      "altura_alambrado_fundos",
      "espacamento_postes_tubos_fundos",
      "comprimento_alambrado_fundo_1",
      "altura_alambrado_fundo_1",
      "espacamento_postes_tubos_fundo_1",
      "comprimento_alambrado_fundo_2",
      "altura_alambrado_fundo_2",
      "espacamento_postes_tubos_fundo_2",
      "travamento",
      "possui_portoes",
      "quantidade_portoes",
      "altura_portoes",
      "comprimento_portoes",
      "possui_tela_superior",
      "cor_tela_superior",
      "possui_tela_sombreamento",
      "cor_tela_sombreamento",
      "possui_sombreamento_lateral_1",
      "altura_sombreamento_lateral_1",
      "comprimento_sombreamento_lateral_1",
      "possui_sombreamento_lateral_2",
      "altura_sombreamento_lateral_2",
      "comprimento_sombreamento_lateral_2",
      "possui_sombreamento_fundo_1",
      "altura_sombreamento_fundo_1",
      "comprimento_sombreamento_fundo_1",
      "possui_sombreamento_fundo_2",
      "altura_sombreamento_fundo_2",
      "comprimento_sombreamento_fundo_2",
    ],
    groups: [
      {
        id: "dados_alambrado",
        title: "Dados do alambrado",
        triggerField: "possui_alambrado",
        fields: [
          "sistema_alambrado",
          "galvanizacao",
          "especificar_galvanizacao",
          "cor_tela_alambrado",
          "cor_tubo_alambrado",
          "cor_tela_malha_alambrado",
          "comprimento_alambrado_laterais",
          "altura_alambrado_laterais",
          "espacamento_postes_tubos_laterais",
          "comprimento_alambrado_lateral_1",
          "altura_alambrado_lateral_1",
          "espacamento_postes_tubos_lateral_1",
          "comprimento_alambrado_lateral_2",
          "altura_alambrado_lateral_2",
          "espacamento_postes_tubos_lateral_2",
          "comprimento_alambrado_fundos",
          "altura_alambrado_fundos",
          "espacamento_postes_tubos_fundos",
          "comprimento_alambrado_fundo_1",
          "altura_alambrado_fundo_1",
          "espacamento_postes_tubos_fundo_1",
          "comprimento_alambrado_fundo_2",
          "altura_alambrado_fundo_2",
          "espacamento_postes_tubos_fundo_2",
          "travamento",
          "possui_portoes",
          "quantidade_portoes",
          "altura_portoes",
          "comprimento_portoes",
        ],
      },
      {
        id: "dados_tela_superior",
        title: "Dados da tela superior",
        triggerField: "possui_tela_superior",
        fields: ["cor_tela_superior"],
      },
      {
        id: "dados_tela_sombreamento",
        title: "Dados da tela de sombreamento",
        triggerField: "possui_tela_sombreamento",
        fields: [
          "cor_tela_sombreamento",
          "possui_sombreamento_lateral_1",
          "altura_sombreamento_lateral_1",
          "comprimento_sombreamento_lateral_1",
          "possui_sombreamento_lateral_2",
          "altura_sombreamento_lateral_2",
          "comprimento_sombreamento_lateral_2",
          "possui_sombreamento_fundo_1",
          "altura_sombreamento_fundo_1",
          "comprimento_sombreamento_fundo_1",
          "possui_sombreamento_fundo_2",
          "altura_sombreamento_fundo_2",
          "comprimento_sombreamento_fundo_2",
        ],
      },
    ],
    layout: {
      possui_alambrado: { span: "full" },
      sistema_alambrado: { span: "full" },
      galvanizacao: { span: "full" },
      especificar_galvanizacao: { span: "full" },
      cor_tela_alambrado: { span: "full", subsectionTitle: "Cores do alambrado" },
      cor_tubo_alambrado: { span: "full" },
      cor_tela_malha_alambrado: { span: "full" },
      comprimento_alambrado_laterais: { span: "full", subsectionTitle: "Laterais" },
      comprimento_alambrado_lateral_1: { span: "full", subsectionTitle: "Lateral 1" },
      comprimento_alambrado_lateral_2: { span: "full", subsectionTitle: "Lateral 2" },
      comprimento_alambrado_fundos: { span: "full", subsectionTitle: "Fundos" },
      comprimento_alambrado_fundo_1: { span: "full", subsectionTitle: "Fundo 1" },
      comprimento_alambrado_fundo_2: { span: "full", subsectionTitle: "Fundo 2" },
      possui_portoes: { span: "full" },
      quantidade_portoes: { span: "full" },
      altura_portoes: { span: 1 },
      comprimento_portoes: { span: 1 },
      possui_tela_superior: { span: "full" },
      cor_tela_superior: { span: "full" },
      possui_tela_sombreamento: { span: "full" },
      cor_tela_sombreamento: { span: "full" },
      possui_sombreamento_lateral_1: { span: "full", subsectionTitle: "Laterais" },
      altura_sombreamento_lateral_1: { span: 1 },
      comprimento_sombreamento_lateral_1: { span: 1 },
      possui_sombreamento_lateral_2: { span: "full" },
      altura_sombreamento_lateral_2: { span: 1 },
      comprimento_sombreamento_lateral_2: { span: 1 },
      possui_sombreamento_fundo_1: { span: "full", subsectionTitle: "Fundos" },
      altura_sombreamento_fundo_1: { span: 1 },
      comprimento_sombreamento_fundo_1: { span: 1 },
      possui_sombreamento_fundo_2: { span: "full" },
      altura_sombreamento_fundo_2: { span: 1 },
      comprimento_sombreamento_fundo_2: { span: 1 },
    },
  },
  fechamentos_padel: {
    id: "fechamentos_padel",
    title: "Alambrado",
    description: "Estrutura combina vidro e tela metálica.",
    fields: ["tipo_estrutura_alambrado_padel"],
  },
  acessorios: {
    id: "acessorios",
    title: "Acessórios",
    fields: ["incluir_rede_tenis"],
  },
  acessorios_quadra_poliesportiva: {
    id: "acessorios_quadra_poliesportiva",
    title: "Acessórios",
    fields: [
      "possui_basquete_adulto",
      "estrutura_basquete_adulto",
      "possui_basquete_juvenil",
      "possui_volei",
      "possui_futebol_futsal",
      "tipo_futsal",
      "possui_tenis",
    ],
    groups: [
      {
        id: "basquete_adulto",
        title: "Basquete adulto",
        triggerField: "possui_basquete_adulto",
        fields: ["estrutura_basquete_adulto"],
      },
      {
        id: "tipo_futsal_group",
        title: "Futebol / Futsal",
        triggerField: "possui_futebol_futsal",
        fields: ["tipo_futsal"],
      },
    ],
    layout: {
      possui_basquete_adulto: { span: "full" },
      possui_basquete_juvenil: { span: "full" },
      possui_volei: { span: "full" },
      possui_futebol_futsal: { span: "full" },
      possui_tenis: { span: "full" },
    },
  },
  acessorios_beach_tenis: {
    id: "acessorios_beach_tenis",
    title: "Acessórios",
    fields: ["possui_acessorio_beach_tenis", "tipo_acessorio_beach_tenis"],
    groups: [
      {
        id: "acessorio_beach_tenis",
        title: "Acessório",
        triggerField: "possui_acessorio_beach_tenis",
        fields: ["tipo_acessorio_beach_tenis"],
      },
    ],
    layout: {
      possui_acessorio_beach_tenis: { span: "full" },
    },
  },
  acessorios_campo: {
    id: "acessorios_campo",
    title: "Acessórios",
    fields: [
      "possui_trave_3x2",
      "possui_trave_4x2",
      "possui_trave_5x2",
      "possui_trave_oficial",
    ],
    layout: {
      possui_trave_3x2: { span: "full" },
      possui_trave_4x2: { span: "full" },
      possui_trave_5x2: { span: "full" },
      possui_trave_oficial: { span: "full" },
    },
  },
  acessorios_pickleball: {
    id: "acessorios_pickleball",
    title: "Acessórios",
    fields: ["possui_rede_pickleball", "tipo_rede_pickleball"],
    groups: [
      {
        id: "rede_pickleball",
        title: "Rede",
        triggerField: "possui_rede_pickleball",
        fields: ["tipo_rede_pickleball"],
      },
    ],
    layout: {
      possui_rede_pickleball: { span: "full" },
    },
  },
  acessorios_padel: {
    id: "acessorios_padel",
    title: "Acessórios",
    fields: ["possui_acessorio_padel"],
    layout: {
      possui_acessorio_padel: { span: "full" },
    },
  },
  observacoes: {
    id: "observacoes",
    title: "Observações",
    fields: ["observacoes"],
    layout: {
      observacoes: { span: "full" },
    },
  },
};

export { sectionRegistry };
