import type { SlideRegistry } from "../types/proposalForm";

const slideRegistry: SlideRegistry = [
  // ─── Globais pré-produto ───────────────────────────────────────────────────

  {
    category: "global",
    slideId: "capa",
    label: "Capa",
    phase: "pre_product",
    order: 1,
    templateFile: "slides/global/capa.pptx",
  },
  {
    category: "global",
    slideId: "portfolio",
    label: "Portfólio de obras",
    phase: "pre_product",
    order: 2,
    templateFile: "slides/global/portfolio.pptx",
  },
  {
    category: "global",
    slideId: "sobre_empresa",
    label: "Com a Playpiso, dá jogo",
    phase: "pre_product",
    order: 3,
    templateFile: "slides/global/sobre_empresa.pptx",
  },
  {
    category: "global",
    slideId: "pilares",
    label: "Pilares",
    phase: "pre_product",
    order: 4,
    templateFile: "slides/global/pilares.pptx",
  },
  {
    category: "global",
    slideId: "parceiros",
    label: "Quem joga com a gente",
    phase: "pre_product",
    order: 5,
    templateFile: "slides/global/parceiros.pptx",
  },
  {
    category: "global",
    slideId: "dados_cliente",
    label: "Dados do cliente",
    phase: "pre_product",
    order: 6,
    templateFile: "slides/global/dados_cliente.pptx",
    placeholders: [
      { placeholder: "{{cliente_nome}}", fieldId: "nome_razao_social" },
      { placeholder: "{{cliente_cnpj}}", fieldId: "cpf_cnpj" },
      { placeholder: "{{cliente_contato}}", fieldId: "nome_contato" },
      { placeholder: "{{cliente_telefone}}", fieldId: "telefone" },
      { placeholder: "{{cliente_email}}", fieldId: "email" },
      { placeholder: "{{obra_local}}", fieldId: "endereco_cliente" },
    ],
  },
  {
    category: "global",
    slideId: "sumario",
    label: "Sumário",
    phase: "pre_product",
    order: 7,
    templateFile: "slides/global/sumario.pptx",
    dynamic: "sumario",
  },

  // ─── Produto: beach_tenis ──────────────────────────────────────────────────

  {
    category: "product",
    slideId: "hero_beach_tenis",
    label: "Quadra de Beach Tennis",
    productId: "beach_tenis",
    orderWithinProduct: 10,
    templateFile: "slides/beach_tenis/hero.pptx",
  },
  {
    category: "conditional",
    slideId: "areia_rio_beach_tenis",
    label: "Sistema de drenagem, mureta e areia de rio lavada",
    productId: "beach_tenis",
    condition: { field: "tipo_areia", operator: "equals", value: "rio" },
    orderWithinProduct: 20,
    templateFile: "slides/beach_tenis/areia_rio.pptx",
  },
  {
    category: "conditional",
    slideId: "areia_quartzo_beach_tenis",
    label: "Sistema de drenagem, mureta e areia de quartzo especial tratada",
    productId: "beach_tenis",
    condition: { field: "tipo_areia", operator: "equals", value: "quartzo" },
    orderWithinProduct: 30,
    templateFile: "slides/beach_tenis/areia_quartzo.pptx",
  },
  {
    category: "conditional",
    slideId: "protecao_eva_beach_tenis",
    label: "Proteção EVA",
    productId: "beach_tenis",
    condition: { field: "possui_eva", operator: "truthy" },
    orderWithinProduct: 40,
    templateFile: "slides/beach_tenis/protecao_eva.pptx",
  },
  {
    category: "conditional",
    slideId: "fechamentos_beach_tenis",
    label: "Fechamentos, Proteções e Iluminação",
    productId: "beach_tenis",
    condition: {
      any: [
        { field: "possui_alambrado", operator: "truthy" },
        { field: "possui_iluminacao", operator: "truthy" },
        { field: "possui_tela_superior", operator: "truthy" },
        { field: "possui_tela_sombreamento", operator: "truthy" },
      ],
    },
    orderWithinProduct: 50,
    templateFile: "slides/beach_tenis/fechamentos_base.pptx",
    dynamic: "fechamentos",
  },
  {
    category: "product",
    slideId: "acessorio_beach_tenis",
    label: "Acessório",
    productId: "beach_tenis",
    orderWithinProduct: 60,
    templateFile: "slides/beach_tenis/acessorio.pptx",
  },
  {
    category: "product",
    slideId: "investimento_beach_tenis",
    label: "Investimento",
    productId: "beach_tenis",
    orderWithinProduct: 70,
    templateFile: "slides/beach_tenis/investimento.pptx",
    dynamic: "investimento",
  },

  // ─── Produto: quadra_tenis ─────────────────────────────────────────────────

  {
    category: "variant",
    slideId: "hero_piso_asfaltico_quadra_tenis",
    label: "Quadra de Tênis — Piso Asfáltico",
    productId: "quadra_tenis",
    variantIds: ["piso_asfaltico"],
    orderWithinProduct: 10,
    templateFile: "slides/quadra_tenis/hero_piso_asfaltico.pptx",
  },
  {
    category: "variant",
    slideId: "hero_saibro_quadra_tenis",
    label: "Quadra de Tênis — Saibro",
    productId: "quadra_tenis",
    variantIds: ["saibro"],
    orderWithinProduct: 10,
    templateFile: "slides/quadra_tenis/hero_saibro.pptx",
  },
  {
    category: "variant",
    slideId: "hero_grama_quadra_tenis",
    label: "Quadra de Tênis — Grama",
    productId: "quadra_tenis",
    variantIds: ["grama"],
    orderWithinProduct: 10,
    templateFile: "slides/quadra_tenis/hero_grama.pptx",
  },
  {
    category: "variant",
    slideId: "specs_piso_asfaltico",
    label: "Piso Asfáltico",
    productId: "quadra_tenis",
    variantIds: ["piso_asfaltico"],
    orderWithinProduct: 20,
    templateFile: "slides/quadra_tenis/specs_piso_asfaltico.pptx",
  },
  {
    category: "variant",
    slideId: "specs_saibro",
    label: "Saibro",
    productId: "quadra_tenis",
    variantIds: ["saibro"],
    orderWithinProduct: 25,
    templateFile: "slides/quadra_tenis/specs_saibro.pptx",
  },
  {
    category: "variant",
    slideId: "specs_grama",
    label: "Grama",
    productId: "quadra_tenis",
    variantIds: ["grama"],
    orderWithinProduct: 27,
    templateFile: "slides/quadra_tenis/specs_grama.pptx",
  },
  {
    category: "conditional",
    slideId: "playcushion_quadra_tenis",
    label: "Playcushion",
    productId: "quadra_tenis",
    variantIds: ["piso_asfaltico"],
    condition: { field: "possui_playcushion", operator: "truthy" },
    orderWithinProduct: 30,
    templateFile: "slides/quadra_tenis/playcushion.pptx",
  },
  {
    category: "conditional",
    slideId: "kit_saibro_quadra_tenis",
    label: "Kit Saibro",
    productId: "quadra_tenis",
    variantIds: ["saibro"],
    condition: { field: "possui_kit_saibro", operator: "truthy" },
    orderWithinProduct: 35,
    templateFile: "slides/quadra_tenis/kit_saibro.pptx",
  },
  {
    category: "conditional",
    slideId: "fechamentos_quadra_tenis",
    label: "Fechamentos, Proteções e Iluminação",
    productId: "quadra_tenis",
    condition: {
      any: [
        { field: "possui_alambrado", operator: "truthy" },
        { field: "possui_iluminacao", operator: "truthy" },
        { field: "possui_tela_superior", operator: "truthy" },
        { field: "possui_tela_sombreamento", operator: "truthy" },
      ],
    },
    orderWithinProduct: 40,
    templateFile: "slides/quadra_tenis/fechamentos_base.pptx",
    dynamic: "fechamentos",
  },
  {
    category: "variant",
    slideId: "cores_piso_asfaltico",
    label: "Sugestões de cores",
    productId: "quadra_tenis",
    variantIds: ["piso_asfaltico"],
    orderWithinProduct: 50,
    templateFile: "slides/quadra_tenis/cores_piso_asfaltico.pptx",
  },
  {
    category: "conditional",
    slideId: "detalhe_construtivo_sem_playcushion",
    label: "Detalhe construtivo",
    productId: "quadra_tenis",
    variantIds: ["piso_asfaltico"],
    condition: { field: "possui_playcushion", operator: "falsy" },
    orderWithinProduct: 60,
    templateFile: "slides/quadra_tenis/detalhe_construtivo_sem_playcushion.pptx",
  },
  {
    category: "conditional",
    slideId: "detalhe_construtivo_com_playcushion",
    label: "Detalhe construtivo com Playcushion",
    productId: "quadra_tenis",
    variantIds: ["piso_asfaltico"],
    condition: { field: "possui_playcushion", operator: "truthy" },
    orderWithinProduct: 70,
    templateFile: "slides/quadra_tenis/detalhe_construtivo_com_playcushion.pptx",
  },
  {
    category: "variant",
    slideId: "investimento_piso_asfaltico_quadra_tenis",
    label: "Investimento",
    productId: "quadra_tenis",
    variantIds: ["piso_asfaltico"],
    orderWithinProduct: 80,
    templateFile: "slides/quadra_tenis/investimento_piso_asfaltico.pptx",
    dynamic: "investimento",
  },
  {
    category: "variant",
    slideId: "investimento_saibro_quadra_tenis",
    label: "Investimento",
    productId: "quadra_tenis",
    variantIds: ["saibro"],
    orderWithinProduct: 80,
    templateFile: "slides/quadra_tenis/investimento_saibro.pptx",
    dynamic: "investimento",
  },
  {
    category: "variant",
    slideId: "investimento_grama_quadra_tenis",
    label: "Investimento",
    productId: "quadra_tenis",
    variantIds: ["grama"],
    orderWithinProduct: 80,
    templateFile: "slides/quadra_tenis/investimento_grama.pptx",
    dynamic: "investimento",
  },

  // ─── Produto: quadra_poliesportiva ─────────────────────────────────────────

  {
    category: "variant",
    slideId: "hero_piso_asfaltico_quadra_poliesportiva",
    label: "Quadra Poliesportiva — Piso Asfáltico",
    productId: "quadra_poliesportiva",
    variantIds: ["piso_asfaltico"],
    orderWithinProduct: 10,
    templateFile: "slides/quadra_poli/hero_piso_asfaltico.pptx",
  },
  {
    category: "variant",
    slideId: "specs_piso_asfaltico_quadra_poliesportiva",
    label: "Especificações — Piso Asfáltico",
    productId: "quadra_poliesportiva",
    variantIds: ["piso_asfaltico"],
    orderWithinProduct: 20,
    templateFile: "slides/quadra_poli/specs_piso_asfaltico.pptx",
  },
  {
    category: "conditional",
    slideId: "acessorios_quadra_poliesportiva",
    label: "Acessórios Esportivos",
    productId: "quadra_poliesportiva",
    condition: {
      any: [
        { field: "possui_basquete_adulto", operator: "truthy" },
        { field: "possui_basquete_juvenil", operator: "truthy" },
        { field: "possui_volei", operator: "truthy" },
        { field: "possui_futebol_futsal", operator: "truthy" },
        { field: "possui_tenis", operator: "truthy" },
      ],
    },
    orderWithinProduct: 30,
    templateFile: "slides/quadra_poli/acessorios_base.pptx",
    dynamic: "acessorios",
  },
  {
    category: "conditional",
    slideId: "fechamentos_quadra_poliesportiva",
    label: "Fechamentos, Proteções e Iluminação",
    productId: "quadra_poliesportiva",
    condition: {
      any: [
        { field: "possui_alambrado", operator: "truthy" },
        { field: "possui_iluminacao", operator: "truthy" },
        { field: "possui_tela_superior", operator: "truthy" },
        { field: "possui_tela_sombreamento", operator: "truthy" },
      ],
    },
    orderWithinProduct: 40,
    templateFile: "slides/quadra_poli/fechamentos_base.pptx",
    dynamic: "fechamentos",
  },
  {
    category: "variant",
    slideId: "cores_piso_asfaltico_quadra_poliesportiva",
    label: "Sugestões de cores",
    productId: "quadra_poliesportiva",
    variantIds: ["piso_asfaltico"],
    orderWithinProduct: 50,
    templateFile: "slides/quadra_poli/cores_piso_asfaltico.pptx",
  },
  {
    category: "variant",
    slideId: "investimento_piso_asfaltico_quadra_poliesportiva",
    label: "Investimento",
    productId: "quadra_poliesportiva",
    variantIds: ["piso_asfaltico"],
    orderWithinProduct: 60,
    templateFile: "slides/quadra_poli/investimento_piso_asfaltico.pptx",
    dynamic: "investimento",
  },

  // ─── Globais pós-produto ───────────────────────────────────────────────────

  // {
  //   category: "global",
  //   slideId: "condicoes_pagamento_direto_a",
  //   label: "Condições de pagamento — Faturamento direto",
  //   phase: "post_product",
  //   order: 1,
  //   templateFile: "slides/global/condicoes_pagamento_direto_a.pptx",
  // },
  // {
  //   category: "global",
  //   slideId: "condicoes_pagamento_direto_b",
  //   label: "Condições de pagamento — Documentos para faturamento direto",
  //   phase: "post_product",
  //   order: 2,
  //   templateFile: "slides/global/condicoes_pagamento_direto_b.pptx",
  // },
  {
    category: "global",
    slideId: "condicoes_pagamento_playpiso",
    label: "Condições de pagamento — Faturamento Playpiso",
    phase: "post_product",
    order: 3,
    templateFile: "slides/global/condicoes_pagamento_playpiso.pptx",
  },
  {
    category: "global",
    slideId: "prazos_garantia",
    label: "Prazos e Garantia",
    phase: "post_product",
    order: 4,
    templateFile: "slides/global/prazos_garantia.pptx",
  },
  {
    category: "global",
    slideId: "regras_contratada",
    label: "Regras do Jogo — Responsabilidades da Contratada",
    phase: "post_product",
    order: 5,
    templateFile: "slides/global/regras_contratada.pptx",
  },
  {
    category: "global",
    slideId: "regras_contratante",
    label: "Regras do Jogo — Responsabilidades do Contratante",
    phase: "post_product",
    order: 6,
    templateFile: "slides/global/regras_contratante.pptx",
  },
  {
    category: "global",
    slideId: "consideracoes_gerais",
    label: "Regras do Jogo — Considerações Gerais",
    phase: "post_product",
    order: 7,
    templateFile: "slides/global/consideracoes_gerais.pptx",
  },
  {
    category: "global",
    slideId: "encerramento",
    label: "Vem pro jogo",
    phase: "post_product",
    order: 8,
    templateFile: "slides/global/encerramento.pptx",
  },
] as const;

export { slideRegistry };
