import type { SlideRegistry } from "../types/proposalForm";

const slideRegistry: SlideRegistry = [
  // ─── Globais pré-produto ───────────────────────────────────────────────────

  {
    category: "global",
    slideId: "capa",
    label: "Capa",
    phase: "pre_product",
    order: 1,
    templateFile: "slides/global/capa.pptx",
  },
  {
    category: "global",
    slideId: "portfolio",
    label: "Portfólio de obras",
    phase: "pre_product",
    order: 2,
    templateFile: "slides/global/portfolio.pptx",
  },
  {
    category: "global",
    slideId: "sobre_empresa",
    label: "Com a Playpiso, dá jogo",
    phase: "pre_product",
    order: 3,
    templateFile: "slides/global/sobre_empresa.pptx",
  },
  {
    category: "global",
    slideId: "pilares",
    label: "Pilares",
    phase: "pre_product",
    order: 4,
    templateFile: "slides/global/pilares.pptx",
  },
  {
    category: "global",
    slideId: "parceiros",
    label: "Quem joga com a gente",
    phase: "pre_product",
    order: 5,
    templateFile: "slides/global/parceiros.pptx",
  },
  {
    category: "global",
    slideId: "dados_cliente",
    label: "Dados do cliente",
    phase: "pre_product",
    order: 6,
    templateFile: "slides/global/dados_cliente.pptx",
    placeholders: [
      { placeholder: "{{cliente_nome}}", fieldId: "nome_razao_social" },
      { placeholder: "{{cliente_cnpj}}", fieldId: "cpf_cnpj" },
      { placeholder: "{{cliente_contato}}", fieldId: "nome_contato" },
      { placeholder: "{{cliente_telefone}}", fieldId: "telefone" },
      { placeholder: "{{cliente_email}}", fieldId: "email" },
      { placeholder: "{{obra_local}}", fieldId: "endereco_cliente" },
    ],
  },
  {
    category: "global",
    slideId: "sumario",
    label: "Sumário",
    phase: "pre_product",
    order: 7,
    templateFile: "slides/global/sumario.pptx",
    dynamic: "sumario",
  },

  // ─── Produto: beach_tenis ──────────────────────────────────────────────────

  {
    category: "product",
    slideId: "hero_beach_tenis",
    label: "Quadra de Beach Tennis",
    productId: "beach_tenis",
    orderWithinProduct: 10,
    templateFile: "slides/beach_tenis/hero.pptx",
  },
  {
    category: "conditional",
    slideId: "areia_rio_beach_tenis",
    label: "Sistema de drenagem, mureta e areia de rio lavada",
    productId: "beach_tenis",
    condition: { field: "tipo_areia", operator: "equals", value: "rio" },
    orderWithinProduct: 20,
    templateFile: "slides/beach_tenis/areia_rio.pptx",
  },
  {
    category: "conditional",
    slideId: "areia_quartzo_beach_tenis",
    label: "Sistema de drenagem, mureta e areia de quartzo especial tratada",
    productId: "beach_tenis",
    condition: { field: "tipo_areia", operator: "equals", value: "quartzo" },
    orderWithinProduct: 30,
    templateFile: "slides/beach_tenis/areia_quartzo.pptx",
  },
  {
    category: "conditional",
    slideId: "protecao_eva_beach_tenis",
    label: "Proteção EVA",
    productId: "beach_tenis",
    condition: { field: "possui_eva", operator: "truthy" },
    orderWithinProduct: 40,
    templateFile: "slides/beach_tenis/protecao_eva.pptx",
  },
  {
    category: "conditional",
    slideId: "fechamentos_beach_tenis",
    label: "Fechamentos, Proteções e Iluminação",
    productId: "beach_tenis",
    condition: {
      any: [
        { field: "possui_alambrado", operator: "truthy" },
        { field: "possui_iluminacao", operator: "truthy" },
        { field: "possui_tela_superior", operator: "truthy" },
        { field: "possui_tela_sombreamento", operator: "truthy" },
      ],
    },
    orderWithinProduct: 50,
    templateFile: "slides/beach_tenis/fechamentos_base.pptx",
    dynamic: "fechamentos",
  },
  {
    category: "product",
    slideId: "acessorio_beach_tenis",
    label: "Acessório",
    productId: "beach_tenis",
    orderWithinProduct: 60,
    templateFile: "slides/beach_tenis/acessorio.pptx",
  },
  {
    category: "product",
    slideId: "investimento_beach_tenis",
    label: "Investimento",
    productId: "beach_tenis",
    orderWithinProduct: 70,
    templateFile: "slides/global/investimento_base.pptx",
    dynamic: "investimento",
  },

  // ─── Produto: quadra_tenis ─────────────────────────────────────────────────

  {
    category: "variant",
    slideId: "hero_piso_asfaltico_quadra_tenis",
    label: "Quadra de Tênis — Piso Asfáltico",
    productId: "quadra_tenis",
    variantIds: ["piso_asfaltico"],
    orderWithinProduct: 10,
    templateFile: "slides/quadra_tenis/hero_piso_asfaltico.pptx",
  },
  {
    category: "variant",
    slideId: "hero_saibro_quadra_tenis",
    label: "Quadra de Tênis — Saibro",
    productId: "quadra_tenis",
    variantIds: ["saibro"],
    orderWithinProduct: 10,
    templateFile: "slides/quadra_tenis/hero_saibro.pptx",
  },
  {
    category: "variant",
    slideId: "hero_grama_natural_quadra_tenis",
    label: "Quadra de Tênis — Grama Natural",
    productId: "quadra_tenis",
    variantIds: ["grama_natural"],
    orderWithinProduct: 10,
    templateFile: "slides/quadra_tenis/hero_grama_natural.pptx",
  },
  {
    category: "variant",
    slideId: "specs_piso_asfaltico",
    label: "Piso Asfáltico",
    productId: "quadra_tenis",
    variantIds: ["piso_asfaltico"],
    orderWithinProduct: 20,
    templateFile: "slides/quadra_tenis/specs_piso_asfaltico.pptx",
  },
  {
    category: "variant",
    slideId: "specs_saibro",
    label: "Saibro",
    productId: "quadra_tenis",
    variantIds: ["saibro"],
    orderWithinProduct: 25,
    templateFile: "slides/quadra_tenis/specs_saibro.pptx",
  },
  {
    category: "variant",
    slideId: "specs_grama_natural",
    label: "Grama Natural",
    productId: "quadra_tenis",
    variantIds: ["grama_natural"],
    orderWithinProduct: 27,
    templateFile: "slides/quadra_tenis/specs_grama_natural.pptx",
  },
  {
    category: "variant",
    slideId: "detalhe_construtivo_grama_natural",
    label: "Detalhe construtivo — Grama Natural",
    productId: "quadra_tenis",
    variantIds: ["grama_natural"],
    orderWithinProduct: 60,
    templateFile: "slides/quadra_tenis/detalhe_construtivo_grama_natural.pptx",
  },
  {
    category: "conditional",
    slideId: "playcushion_quadra_tenis",
    label: "Playcushion",
    productId: "quadra_tenis",
    variantIds: ["piso_asfaltico"],
    condition: { field: "possui_playcushion", operator: "truthy" },
    orderWithinProduct: 30,
    templateFile: "slides/quadra_tenis/playcushion.pptx",
  },
  {
    category: "conditional",
    slideId: "kit_saibro_quadra_tenis",
    label: "Kit Saibro",
    productId: "quadra_tenis",
    variantIds: ["saibro"],
    condition: { field: "possui_kit_saibro", operator: "truthy" },
    orderWithinProduct: 35,
    templateFile: "slides/quadra_tenis/kit_saibro.pptx",
  },
  {
    category: "conditional",
    slideId: "fechamentos_quadra_tenis",
    label: "Fechamentos, Proteções e Iluminação",
    productId: "quadra_tenis",
    condition: {
      any: [
        { field: "possui_alambrado", operator: "truthy" },
        { field: "possui_iluminacao", operator: "truthy" },
        { field: "possui_tela_superior", operator: "truthy" },
        { field: "possui_tela_sombreamento", operator: "truthy" },
      ],
    },
    orderWithinProduct: 40,
    templateFile: "slides/quadra_tenis/fechamentos_base.pptx",
    dynamic: "fechamentos",
  },
  {
    category: "variant",
    slideId: "cores_piso_asfaltico",
    label: "Sugestões de cores",
    productId: "quadra_tenis",
    variantIds: ["piso_asfaltico"],
    orderWithinProduct: 50,
    templateFile: "slides/quadra_tenis/cores_piso_asfaltico.pptx",
  },
  {
    category: "conditional",
    slideId: "detalhe_construtivo_sem_playcushion",
    label: "Detalhe construtivo",
    productId: "quadra_tenis",
    variantIds: ["piso_asfaltico"],
    condition: { field: "possui_playcushion", operator: "falsy" },
    orderWithinProduct: 60,
    templateFile: "slides/quadra_tenis/detalhe_construtivo_sem_playcushion.pptx",
  },
  {
    category: "conditional",
    slideId: "detalhe_construtivo_com_playcushion",
    label: "Detalhe construtivo com Playcushion",
    productId: "quadra_tenis",
    variantIds: ["piso_asfaltico"],
    condition: { field: "possui_playcushion", operator: "truthy" },
    orderWithinProduct: 70,
    templateFile: "slides/quadra_tenis/detalhe_construtivo_com_playcushion.pptx",
  },
  {
    category: "variant",
    slideId: "investimento_piso_asfaltico_quadra_tenis",
    label: "Investimento",
    productId: "quadra_tenis",
    variantIds: ["piso_asfaltico"],
    orderWithinProduct: 80,
    templateFile: "slides/global/investimento_base.pptx",
    dynamic: "investimento",
  },
  {
    category: "variant",
    slideId: "investimento_saibro_quadra_tenis",
    label: "Investimento",
    productId: "quadra_tenis",
    variantIds: ["saibro"],
    orderWithinProduct: 80,
    templateFile: "slides/global/investimento_base.pptx",
    dynamic: "investimento",
  },
  {
    category: "variant",
    slideId: "investimento_grama_natural_quadra_tenis",
    label: "Investimento",
    productId: "quadra_tenis",
    variantIds: ["grama_natural"],
    orderWithinProduct: 80,
    templateFile: "slides/global/investimento_base.pptx",
    dynamic: "investimento",
  },

  // ─── Produto: quadra_poliesportiva ─────────────────────────────────────────

  {
    category: "variant",
    slideId: "hero_piso_asfaltico_quadra_poliesportiva",
    label: "Quadra Poliesportiva — Piso Asfáltico",
    productId: "quadra_poliesportiva",
    variantIds: ["piso_asfaltico"],
    orderWithinProduct: 10,
    templateFile: "slides/quadra_poli/hero_piso_asfaltico.pptx",
  },
  {
    category: "variant",
    slideId: "hero_assoalho_quadra_poliesportiva",
    label: "Quadra Poliesportiva — Assoalho",
    productId: "quadra_poliesportiva",
    variantIds: ["assoalho"],
    orderWithinProduct: 10,
    templateFile: "slides/quadra_poli/hero_assoalho.pptx",
  },
  {
    category: "variant",
    slideId: "hero_poliuretano_quadra_poliesportiva",
    label: "Quadra Poliesportiva — Poliuretano",
    productId: "quadra_poliesportiva",
    variantIds: ["poliuretano"],
    orderWithinProduct: 10,
    templateFile: "slides/quadra_poli/hero_poliuretano.pptx",
  },
  {
    category: "variant",
    slideId: "specs_piso_asfaltico_quadra_poliesportiva",
    label: "Especificações — Piso Asfáltico",
    productId: "quadra_poliesportiva",
    variantIds: ["piso_asfaltico"],
    orderWithinProduct: 20,
    templateFile: "slides/quadra_poli/specs_piso_asfaltico.pptx",
  },
  {
    category: "variant",
    slideId: "specs_assoalho_quadra_poliesportiva",
    label: "Especificações — Assoalho",
    productId: "quadra_poliesportiva",
    variantIds: ["assoalho"],
    orderWithinProduct: 20,
    templateFile: "slides/quadra_poli/specs_assoalho.pptx",
  },
  {
    category: "variant",
    slideId: "specs_poliuretano_quadra_poliesportiva",
    label: "Especificações — Poliuretano",
    productId: "quadra_poliesportiva",
    variantIds: ["poliuretano"],
    orderWithinProduct: 20,
    templateFile: "slides/quadra_poli/specs_poliuretano.pptx",
  },
  {
    category: "conditional",
    slideId: "acessorios_quadra_poliesportiva",
    label: "Acessórios Esportivos",
    productId: "quadra_poliesportiva",
    condition: {
      any: [
        { field: "possui_basquete_adulto", operator: "truthy" },
        { field: "possui_basquete_juvenil", operator: "truthy" },
        { field: "possui_volei", operator: "truthy" },
        { field: "possui_futebol_futsal", operator: "truthy" },
        { field: "possui_tenis", operator: "truthy" },
      ],
    },
    orderWithinProduct: 30,
    templateFile: "slides/quadra_poli/acessorios_base.pptx",
    dynamic: "acessorios",
  },
  {
    category: "conditional",
    slideId: "fechamentos_quadra_poliesportiva",
    label: "Fechamentos, Proteções e Iluminação",
    productId: "quadra_poliesportiva",
    condition: {
      any: [
        { field: "possui_alambrado", operator: "truthy" },
        { field: "possui_iluminacao", operator: "truthy" },
        { field: "possui_tela_superior", operator: "truthy" },
        { field: "possui_tela_sombreamento", operator: "truthy" },
      ],
    },
    orderWithinProduct: 40,
    templateFile: "slides/quadra_poli/fechamentos_base.pptx",
    dynamic: "fechamentos",
  },
  {
    category: "variant",
    slideId: "detalhe_construtivo_assoalho_quadra_poliesportiva",
    label: "Detalhe construtivo — Assoalho",
    productId: "quadra_poliesportiva",
    variantIds: ["assoalho"],
    orderWithinProduct: 45,
    templateFile: "slides/quadra_poli/detalhe_construtivo_assoalho.pptx",
  },
  {
    category: "variant",
    slideId: "detalhe_construtivo_poliuretano_quadra_poliesportiva",
    label: "Detalhe construtivo — Poliuretano",
    productId: "quadra_poliesportiva",
    variantIds: ["poliuretano"],
    orderWithinProduct: 25,
    templateFile: "slides/quadra_poli/detalhe_construtivo_poliuretano.pptx",
  },
  {
    category: "conditional",
    slideId: "recomendacao_execucao_poliuretano_quadra_poliesportiva",
    label: "Recomendação de execução — Poliuretano sobre laje/concreto",
    productId: "quadra_poliesportiva",
    variantIds: ["poliuretano"],
    condition: {
      field: "tipo_terreno",
      operator: "equals",
      value: "laje_concreto",
    },
    orderWithinProduct: 47,
    templateFile:
      "slides/quadra_poli/recomendacao_execucao_poliuretano.pptx",
  },
  {
    category: "variant",
    slideId: "cores_piso_asfaltico_quadra_poliesportiva",
    label: "Sugestões de cores",
    productId: "quadra_poliesportiva",
    variantIds: ["piso_asfaltico"],
    orderWithinProduct: 50,
    templateFile: "slides/quadra_poli/cores_piso_asfaltico.pptx",
  },
  {
    category: "variant",
    slideId: "investimento_piso_asfaltico_quadra_poliesportiva",
    label: "Investimento",
    productId: "quadra_poliesportiva",
    variantIds: ["piso_asfaltico"],
    orderWithinProduct: 60,
    templateFile: "slides/global/investimento_base.pptx",
    dynamic: "investimento",
  },
  {
    category: "variant",
    slideId: "investimento_assoalho_quadra_poliesportiva",
    label: "Investimento — Assoalho",
    productId: "quadra_poliesportiva",
    variantIds: ["assoalho"],
    orderWithinProduct: 60,
    templateFile: "slides/global/investimento_base.pptx",
    dynamic: "investimento",
  },
  {
    category: "variant",
    slideId: "investimento_poliuretano_quadra_poliesportiva",
    label: "Investimento — Poliuretano",
    productId: "quadra_poliesportiva",
    variantIds: ["poliuretano"],
    orderWithinProduct: 60,
    templateFile: "slides/global/investimento_base.pptx",
    dynamic: "investimento",
  },

  // ─── Produto: padel ────────────────────────────────────────────────────────

  {
    category: "product",
    slideId: "hero_padel",
    label: "Quadra de Padel",
    productId: "padel",
    orderWithinProduct: 10,
    templateFile: "slides/padel/hero.pptx",
  },
  {
    category: "product",
    slideId: "specs_padel",
    label: "Especificações do Padel",
    productId: "padel",
    orderWithinProduct: 20,
    templateFile: "slides/padel/specs_padel.pptx",
  },
  {
    category: "conditional",
    slideId: "acessorios_padel",
    label: "Acessórios",
    productId: "padel",
    condition: { field: "possui_acessorio_padel", operator: "truthy" },
    orderWithinProduct: 30,
    templateFile: "slides/padel/acessorios_base.pptx",
    dynamic: "acessorios",
  },
  {
    category: "conditional",
    slideId: "fechamentos_padel",
    label: "Alambrado, Proteções e Iluminação",
    productId: "padel",
    condition: {
      any: [
        { field: "possui_alambrado", operator: "truthy" },
        { field: "possui_iluminacao", operator: "truthy" },
        { field: "possui_tela_superior", operator: "truthy" },
        { field: "possui_tela_sombreamento", operator: "truthy" },
      ],
    },
    orderWithinProduct: 40,
    templateFile: "slides/padel/fechamentos_base.pptx",
    dynamic: "fechamentos",
  },
  {
    category: "product",
    slideId: "investimento_padel",
    label: "Investimento",
    productId: "padel",
    orderWithinProduct: 70,
    templateFile: "slides/global/investimento_base.pptx",
    dynamic: "investimento",
  },

  // ─── Produto: pickleball ───────────────────────────────────────────────────

  {
    category: "product",
    slideId: "hero_pickleball",
    label: "Quadra de Pickleball",
    productId: "pickleball",
    orderWithinProduct: 10,
    templateFile: "slides/pickleball/hero.pptx",
  },
  {
    category: "product",
    slideId: "specs_pickleball",
    label: "Especificações do Pickleball",
    productId: "pickleball",
    orderWithinProduct: 20,
    templateFile: "slides/pickleball/specs_pickleball.pptx",
  },
  {
    category: "conditional",
    slideId: "acessorios_pickleball",
    label: "Acessórios",
    productId: "pickleball",
    condition: { field: "possui_rede_pickleball", operator: "truthy" },
    orderWithinProduct: 30,
    templateFile: "slides/pickleball/acessorios_base.pptx",
    dynamic: "acessorios",
  },
  {
    category: "conditional",
    slideId: "fechamentos_pickleball",
    label: "Fechamentos, Proteções e Iluminação",
    productId: "pickleball",
    condition: {
      any: [
        { field: "possui_alambrado", operator: "truthy" },
        { field: "possui_iluminacao", operator: "truthy" },
        { field: "possui_tela_superior", operator: "truthy" },
        { field: "possui_tela_sombreamento", operator: "truthy" },
      ],
    },
    orderWithinProduct: 40,
    templateFile: "slides/pickleball/fechamentos_base.pptx",
    dynamic: "fechamentos",
  },
  {
    category: "product",
    slideId: "investimento_pickleball",
    label: "Investimento",
    productId: "pickleball",
    orderWithinProduct: 70,
    templateFile: "slides/global/investimento_base.pptx",
    dynamic: "investimento",
  },

  // ─── Produto: softplay ─────────────────────────────────────────────────────

  {
    category: "product",
    slideId: "hero_softplay",
    label: "Softplay Playground",
    productId: "softplay",
    orderWithinProduct: 10,
    templateFile: "slides/softplay/hero.pptx",
  },
  {
    category: "product",
    slideId: "specs_softplay",
    label: "Especificações do Softplay",
    productId: "softplay",
    orderWithinProduct: 20,
    templateFile: "slides/softplay/specs_softplay.pptx",
    placeholders: [
      { placeholder: "{{espessura_sbr}}", fieldId: "espessura_sbr" },
      { placeholder: "{{espessura_epdm}}", fieldId: "espessura_epdm" },
      { placeholder: "{{espessura_total}}", fieldId: "espessura_total" },
      { placeholder: "{{tipo_epdm}}", fieldId: "tipo_epdm" },
    ],
  },
  {
    category: "product",
    slideId: "amostra_softplay",
    label: "Amostra",
    productId: "softplay",
    orderWithinProduct: 30,
    templateFile: "slides/softplay/amostra.pptx",
  },
  {
    category: "product",
    slideId: "cores_softplay",
    label: "Sugestões de cores",
    productId: "softplay",
    orderWithinProduct: 40,
    templateFile: "slides/softplay/cores.pptx",
  },
  {
    category: "conditional",
    slideId: "recomendacao_execucao_softplay",
    label: "Recomendação de execução — sobre laje/concreto",
    productId: "softplay",
    condition: {
      field: "tipo_terreno",
      operator: "equals",
      value: "laje_concreto",
    },
    orderWithinProduct: 50,
    templateFile: "slides/softplay/recomendacao_execucao_softplay.pptx",
  },
  {
    category: "product",
    slideId: "investimento_softplay",
    label: "Investimento",
    productId: "softplay",
    orderWithinProduct: 70,
    templateFile: "slides/global/investimento_base.pptx",
    dynamic: "investimento",
  },

  // ─── Globais pós-produto ───────────────────────────────────────────────────

  // {
  //   category: "global",
  //   slideId: "condicoes_pagamento_direto_a",
  //   label: "Condições de pagamento — Faturamento direto",
  //   phase: "post_product",
  //   order: 1,
  //   templateFile: "slides/global/condicoes_pagamento_direto_a.pptx",
  // },
  // {
  //   category: "global",
  //   slideId: "condicoes_pagamento_direto_b",
  //   label: "Condições de pagamento — Documentos para faturamento direto",
  //   phase: "post_product",
  //   order: 2,
  //   templateFile: "slides/global/condicoes_pagamento_direto_b.pptx",
  // },
  {
    category: "global",
    slideId: "condicoes_pagamento_playpiso",
    label: "Condições de pagamento — Faturamento Playpiso",
    phase: "post_product",
    order: 3,
    templateFile: "slides/global/condicoes_pagamento_playpiso.pptx",
  },
  {
    category: "global",
    slideId: "prazos_garantia",
    label: "Prazos e Garantia",
    phase: "post_product",
    order: 4,
    templateFile: "slides/global/prazos_garantia.pptx",
  },
  {
    category: "global",
    slideId: "regras_contratada",
    label: "Regras do Jogo — Responsabilidades da Contratada",
    phase: "post_product",
    order: 5,
    templateFile: "slides/global/regras_contratada.pptx",
  },
  {
    category: "global",
    slideId: "regras_contratante",
    label: "Regras do Jogo — Responsabilidades do Contratante",
    phase: "post_product",
    order: 6,
    templateFile: "slides/global/regras_contratante.pptx",
  },
  {
    category: "global",
    slideId: "consideracoes_gerais",
    label: "Regras do Jogo — Considerações Gerais",
    phase: "post_product",
    order: 7,
    templateFile: "slides/global/consideracoes_gerais.pptx",
  },
  {
    category: "global",
    slideId: "encerramento",
    label: "Vem pro jogo",
    phase: "post_product",
    order: 8,
    templateFile: "slides/global/encerramento.pptx",
  },
] as const;

export { slideRegistry };
