namespace PlaypisoIntranet.DTOs;

public record ProposalSummaryResponse(
    Guid Id,
    string NumeroProposta,
    string Status,
    string NomeRazaoSocial,
    string Cidade,
    string Estado,
    DateOnly? DataSolicitacao,
    DateOnly? DataEnvio,
    string? PptxUrl,
    string? XlsxUrl,
    string CreatedByEmail,
    string? CreatedByName,
    string? GeneratedByUserId,
    string? GeneratedByEmail,
    string? GeneratedByName,
    DateTime? GeneratedAt,
    DateTime CreatedAt,
    int TotalProducts
);

public record ProposalDetailResponse(
    Guid Id,
    string NumeroProposta,
    string Status,
    DateOnly? DataSolicitacao,
    DateOnly? DataEnvio,
    string NomeRazaoSocial,
    string? CpfCnpj,
    string? NomeContato,
    string? Telefone,
    string? EmailCliente,
    string EnderecoCliente,
    string LocalObra,
    string Cidade,
    string Estado,
    string TipoProjeto,
    string? PptxUrl,
    string? XlsxUrl,
    string CreatedByUserId,
    string? CreatedByEmail,
    string? CreatedByName,
    string? GeneratedByUserId,
    string? GeneratedByEmail,
    string? GeneratedByName,
    DateTime? GeneratedAt,
    DateTime CreatedAt,
    DateTime UpdatedAt,
    IEnumerable<ProductGroupResponse> ProductGroups
);

public record ProductGroupResponse(
    Guid Id,
    string ProductId,
    string VariantId,
    int Quantity,
    int GroupIndex,
    decimal? Largura,
    decimal? Comprimento,
    decimal? AreaTotal,
    string? TipoTerreno,
    string? DificuldadeAcesso,
    string? ResponsavelMaterialPedreira,
    bool PossuiIluminacao,
    bool? IluminacaoFixadaAlambrado,
    int? QuantidadePostesIluminacao,
    decimal? AlturaPostesIluminacao,
    int? QuantidadeProjetores,
    string? PotenciaProjetores,
    string? EspecificarPotenciaProjetores,
    int? QuantidadeCruzetas,
    string? ResponsavelLigacaoEletrica,
    string? TipoColigacao,
    bool PossuiAlambrado,
    string? Galvanizacao,
    string? EspecificarGalvanizacao,
    bool? PossuiTrelica,
    string? Travamento,
    int? QuantidadePortoes,
    decimal? AlturaPortoes,
    decimal? ComprimentoPortoes,
    bool? PossuiTelaSuperior,
    bool? PossuiTelaSombreamento,
    decimal? LarguraSombreamento,
    decimal? ComprimentoSombreamento,
    string? Observacoes,
    string Specs
);
