import type { FieldDefinition } from "../types/proposalForm";

const fieldRegistry: Record<string, FieldDefinition> = {
  nome_razao_social: {
    id: "nome_razao_social",
    label: "Nome/Razão social",
    type: "text",
    required: true,
    placeholder: "Ex: Condomínio Exemplo",
    xlsxKey: "cliente_nome",
    pptxKey: "cliente_nome",
  },
  cpf_cnpj: {
    id: "cpf_cnpj",
    label: "CPF/CNPJ",
    type: "text",
    placeholder: "Ex: 00.000.000/0001-00",
    required: true,
    xlsxKey: "cliente_documento",
    pptxKey: "cliente_documento",
  },
  nome_contato: {
    id: "nome_contato",
    label: "Nome do contato",
    type: "text",
    required: true,
    xlsxKey: "contato_nome",
    pptxKey: "contato_nome",
  },
  telefone: {
    id: "telefone",
    label: "Telefone",
    type: "text",
    placeholder: "Ex: (11) 99999-9999",
    required: true,
    xlsxKey: "telefone",
    pptxKey: "telefone",
  },
  email: {
    id: "email",
    label: "E-mail",
    type: "email",
    placeholder: "Ex: contato@email.com",
    required: true,
    xlsxKey: "email",
    pptxKey: "email",
  },
  numero_proposta: {
    id: "numero_proposta",
    label: "Número da proposta",
    type: "text",
    required: true,
    placeholder: "Ex: P001",
    xlsxKey: "numero_proposta",
    pptxKey: "numero_proposta",
  },
  data_solicitacao: {
    id: "data_solicitacao",
    label: "Data de solicitação",
    type: "date",
    xlsxKey: "data_solicitacao",
    pptxKey: "data_solicitacao",
  },
  data_envio: {
    id: "data_envio",
    label: "Data de envio",
    type: "date",
    xlsxKey: "data_envio",
    pptxKey: "data_envio",
  },
  endereco_obra: {
    id: "endereco_obra",
    label: "Endereço da obra",
    type: "text",
    required: true,
    xlsxKey: "endereco_obra",
    pptxKey: "endereco_obra",
  },
  local_obra: {
    id: "local_obra",
    label: "Local da obra",
    type: "text",
    placeholder: "Ex: Galpão, Bloco A",
    required: true,
    xlsxKey: "local_obra",
    pptxKey: "local_obra",
  },
  cidade: {
    id: "cidade",
    label: "Cidade",
    type: "text",
    required: true,
    xlsxKey: "cidade",
    pptxKey: "cidade",
  },
  estado: {
    id: "estado",
    label: "Estado",
    type: "text",
    required: true,
    placeholder: "Ex: SP",
    xlsxKey: "estado",
    pptxKey: "estado",
  },
  tipo_projeto: {
    id: "tipo_projeto",
    label: "Tipo de projeto",
    type: "select",
    required: true,
    optionsKey: "tipo_projeto",
    xlsxKey: "tipo_projeto",
    pptxKey: "tipo_projeto",
  },
  variante_quadra_tenis: {
    id: "variante_quadra_tenis",
    label: "Variante da Quadra de Tênis",
    type: "select",
    required: true,
    defaultValue: "piso_asfaltico",
    optionsKey: "variante_quadra_tenis",
    xlsxKey: "variante_quadra_tenis",
    pptxKey: "variante_quadra_tenis",
  },
  variante_quadra_poliesportiva: {
    id: "variante_quadra_poliesportiva",
    label: "Variante da Quadra Poliesportiva",
    type: "select",
    required: true,
    defaultValue: "piso_asfaltico",
    optionsKey: "variante_quadra_poliesportiva",
    xlsxKey: "variante_quadra_poliesportiva",
    pptxKey: "variante_quadra_poliesportiva",
  },
  variante_beach_tenis: {
    id: "variante_beach_tenis",
    label: "Variante do Beach Tennis",
    type: "select",
    required: true,
    defaultValue: "padrao",
    optionsKey: "variante_beach_tenis",
    xlsxKey: "variante_beach_tenis",
    pptxKey: "variante_beach_tenis",
  },
  variante_campo: {
    id: "variante_campo",
    label: "Variante do Campo",
    type: "select",
    required: true,
    defaultValue: "natural",
    optionsKey: "variante_campo",
    xlsxKey: "variante_campo",
    pptxKey: "variante_campo",
  },
  variante_pickleball: {
    id: "variante_pickleball",
    label: "Variante do Pickleball",
    type: "select",
    required: true,
    defaultValue: "padrao",
    optionsKey: "variante_pickleball",
    xlsxKey: "variante_pickleball",
    pptxKey: "variante_pickleball",
  },
  variante_padel: {
    id: "variante_padel",
    label: "Variante do Padel",
    type: "select",
    required: true,
    defaultValue: "grama_sintetica",
    optionsKey: "variante_padel",
    xlsxKey: "variante_padel",
    pptxKey: "variante_padel",
  },
  variante_squash: {
    id: "variante_squash",
    label: "Variante do Squash",
    type: "select",
    required: true,
    defaultValue: "padrao",
    optionsKey: "variante_squash",
    xlsxKey: "variante_squash",
    pptxKey: "variante_squash",
  },
  variante_pista: {
    id: "variante_pista",
    label: "Variante da Pista",
    type: "select",
    required: true,
    defaultValue: "mondo",
    optionsKey: "variante_pista",
    xlsxKey: "variante_pista",
    pptxKey: "variante_pista",
  },
  variante_garagem_epoxi: {
    id: "variante_garagem_epoxi",
    label: "Variante da Garagem Epóxi",
    type: "select",
    required: true,
    defaultValue: "padrao",
    optionsKey: "variante_garagem_epoxi",
    xlsxKey: "variante_garagem_epoxi",
    pptxKey: "variante_garagem_epoxi",
  },
  variante_softplay: {
    id: "variante_softplay",
    label: "Variante do Softplay",
    type: "select",
    required: true,
    defaultValue: "padrao",
    optionsKey: "variante_softplay",
    xlsxKey: "variante_softplay",
    pptxKey: "variante_softplay",
  },
  numero_raias: {
    id: "numero_raias",
    label: "Número de raias",
    type: "number",
    unit: "un",
    required: true,
    xlsxKey: "numero_raias",
    pptxKey: "numero_raias",
  },
  opcao_pu_200_b_pista: {
    id: "opcao_pu_200_b_pista",
    label: "Opção PU 200 B",
    type: "select",
    required: true,
    optionsKey: "opcao_pu_200_b_pista",
    xlsxKey: "opcao_pu_200_b_pista",
    pptxKey: "opcao_pu_200_b_pista",
  },
  largura: {
    id: "largura",
    label: "Largura",
    type: "number",
    unit: "m",
    required: true,
    placeholder: "Ex: 18",
    description: "Largura da área principal da quadra em metros.",
    xlsxKey: "largura_m",
    pptxKey: "largura",
  },
  comprimento: {
    id: "comprimento",
    label: "Comprimento",
    type: "number",
    unit: "m",
    required: true,
    placeholder: "Ex: 36",
    description: "Comprimento da área principal da quadra em metros.",
    xlsxKey: "comprimento_m",
    pptxKey: "comprimento",
  },
  area_total: {
    id: "area_total",
    label: "Área total",
    type: "number",
    unit: "m2",
    required: true,
    description:
      "Área calculada automaticamente por largura x comprimento, com ajuste manual permitido.",
    xlsxKey: "area_total_m2",
    pptxKey: "area_total",
  },
  tipo_terreno: {
    id: "tipo_terreno",
    label: "Tipo de terreno",
    type: "select",
    required: true,
    defaultValue: "solo_preparado",
    optionsKey: "tipo_terreno",
    xlsxKey: "tipo_terreno",
    pptxKey: "tipo_terreno",
  },
  dificuldade_acesso: {
    id: "dificuldade_acesso",
    label: "Dificuldade de acesso",
    type: "select",
    required: true,
    defaultValue: "facil",
    optionsKey: "dificuldade_acesso",
    description:
      "Indica a dificuldade logística para entrada de equipe, equipamentos e materiais na obra.",
    xlsxKey: "dificuldade_acesso",
    pptxKey: "dificuldade_acesso",
  },
  responsavel_material_pedreira: {
    id: "responsavel_material_pedreira",
    label: "Responsável pelo material de pedreira",
    type: "select",
    required: true,
    defaultValue: "cliente",
    optionsKey: "responsavel_material_pedreira",
    xlsxKey: "responsavel_material_pedreira",
    pptxKey: "responsavel_material_pedreira",
  },
  cor_piso_asfaltico: {
    id: "cor_piso_asfaltico",
    label: "Cor",
    type: "select",
    required: true,
    optionsKey: "cor_piso_asfaltico",
    xlsxKey: "cor_piso_asfaltico",
    pptxKey: "cor_piso_asfaltico",
  },
  especificar_cor: {
    id: "especificar_cor",
    label: "Especificar cor",
    type: "text",
    placeholder: "Descreva a cor desejada",
    xlsxKey: "especificar_cor",
    pptxKey: "especificar_cor",
  },
  cor_pickleball: {
    id: "cor_pickleball",
    label: "Cor",
    type: "select",
    required: true,
    optionsKey: "cor_pickleball",
    xlsxKey: "cor_pickleball",
    pptxKey: "cor_pickleball",
  },
  especificar_cor_pickleball: {
    id: "especificar_cor_pickleball",
    label: "Especificar cor",
    type: "text",
    placeholder: "Descreva a cor desejada",
    xlsxKey: "especificar_cor_pickleball",
    pptxKey: "especificar_cor_pickleball",
  },
  possui_playcushion: {
    id: "possui_playcushion",
    label: "Incluir PlayCushion?",
    type: "checkbox",
    defaultValue: false,
    xlsxKey: "possui_playcushion",
    pptxKey: "possui_playcushion",
  },
  possui_kit_saibro: {
    id: "possui_kit_saibro",
    label: "Incluir Kit Saibro?",
    type: "checkbox",
    defaultValue: false,
    xlsxKey: "possui_kit_saibro",
    pptxKey: "possui_kit_saibro",
  },
  tipo_grama: {
    id: "tipo_grama",
    label: "Tipo de grama",
    type: "select",
    required: true,
    optionsKey: "tipo_grama",
    xlsxKey: "tipo_grama",
    pptxKey: "tipo_grama",
  },
  especificar_tipo_grama: {
    id: "especificar_tipo_grama",
    label: "Especificar tipo de grama",
    type: "text",
    placeholder: "Descreva o tipo de grama",
    xlsxKey: "especificar_tipo_grama",
    pptxKey: "especificar_tipo_grama",
  },
  tipo_grama_natural: {
    id: "tipo_grama_natural",
    label: "Tipo de grama natural",
    type: "select",
    required: true,
    optionsKey: "tipo_grama_natural",
    xlsxKey: "tipo_grama_natural",
    pptxKey: "tipo_grama_natural",
  },
  especificar_tipo_grama_natural: {
    id: "especificar_tipo_grama_natural",
    label: "Especificar tipo de grama natural",
    type: "text",
    placeholder: "Descreva o tipo de grama natural",
    xlsxKey: "especificar_tipo_grama_natural",
    pptxKey: "especificar_tipo_grama_natural",
  },
  tipo_grama_sintetica: {
    id: "tipo_grama_sintetica",
    label: "Tipo de grama sintética",
    type: "select",
    required: true,
    optionsKey: "tipo_grama_sintetica",
    xlsxKey: "tipo_grama_sintetica",
    pptxKey: "tipo_grama_sintetica",
  },
  especificar_tipo_grama_sintetica: {
    id: "especificar_tipo_grama_sintetica",
    label: "Especificar tipo de grama sintética",
    type: "text",
    placeholder: "Descreva o tipo de grama sintética",
    xlsxKey: "especificar_tipo_grama_sintetica",
    pptxKey: "especificar_tipo_grama_sintetica",
  },
  tipo_grama_padel: {
    id: "tipo_grama_padel",
    label: "Tipo de grama",
    type: "select",
    required: true,
    optionsKey: "tipo_grama_padel",
    xlsxKey: "tipo_grama_padel",
    pptxKey: "tipo_grama_padel",
  },
  altura_grama_sintetica: {
    id: "altura_grama_sintetica",
    label: "Altura da grama sintética",
    type: "select",
    required: true,
    optionsKey: "altura_grama_sintetica",
    xlsxKey: "altura_grama_sintetica",
    pptxKey: "altura_grama_sintetica",
  },
  base_drenante: {
    id: "base_drenante",
    label: "Base drenante",
    type: "select",
    required: true,
    optionsKey: "base_drenante",
    xlsxKey: "base_drenante",
    pptxKey: "base_drenante",
  },
  possui_shockpad: {
    id: "possui_shockpad",
    label: "Possui shockpad?",
    type: "checkbox",
    defaultValue: false,
    xlsxKey: "possui_shockpad",
    pptxKey: "possui_shockpad",
  },
  tipo_madeira: {
    id: "tipo_madeira",
    label: "Tipo de madeira",
    type: "select",
    required: true,
    optionsKey: "tipo_madeira",
    xlsxKey: "tipo_madeira",
    pptxKey: "tipo_madeira",
  },
  anti_chama: {
    id: "anti_chama",
    label: "Anti-chama",
    type: "checkbox",
    defaultValue: false,
    xlsxKey: "anti_chama",
    pptxKey: "anti_chama",
  },
  condicao_base_piso: {
    id: "condicao_base_piso",
    label: "Condição da base/piso",
    type: "select",
    required: true,
    optionsKey: "condicao_base_piso",
    xlsxKey: "condicao_base_piso",
    pptxKey: "condicao_base_piso",
  },
  condicao_base_piso_garagem_epoxi: {
    id: "condicao_base_piso_garagem_epoxi",
    label: "Condição da base/piso",
    type: "select",
    required: true,
    optionsKey: "condicao_base_piso",
    xlsxKey: "condicao_base_piso_garagem_epoxi",
    pptxKey: "condicao_base_piso_garagem_epoxi",
  },
  tipo_poliuretano: {
    id: "tipo_poliuretano",
    label: "Tipo de poliuretano",
    type: "select",
    required: true,
    optionsKey: "tipo_poliuretano",
    xlsxKey: "tipo_poliuretano",
    pptxKey: "tipo_poliuretano",
  },
  tipo_areia: {
    id: "tipo_areia",
    label: "Tipo de areia",
    type: "select",
    required: true,
    optionsKey: "tipo_areia",
    xlsxKey: "tipo_areia",
    pptxKey: "tipo_areia",
  },
  espessura_areia: {
    id: "espessura_areia",
    label: "Espessura da areia",
    type: "number",
    unit: "cm",
    required: true,
    placeholder: "Ex: 30",
    xlsxKey: "espessura_areia",
    pptxKey: "espessura_areia",
  },
  possui_eva: {
    id: "possui_eva",
    label: "Possui proteção EVA?",
    type: "checkbox",
    defaultValue: false,
    xlsxKey: "possui_eva",
    pptxKey: "possui_eva",
  },
  espessura_sbr: {
    id: "espessura_sbr",
    label: "Espessura de SBR",
    type: "number",
    unit: "cm",
    required: true,
    placeholder: "Ex: 3",
    xlsxKey: "espessura_sbr",
    pptxKey: "espessura_sbr",
  },
  espessura_epdm: {
    id: "espessura_epdm",
    label: "Espessura de EPDM",
    type: "number",
    unit: "cm",
    required: true,
    defaultValue: 1,
    placeholder: "Ex: 1",
    xlsxKey: "espessura_epdm",
    pptxKey: "espessura_epdm",
  },
  possui_iluminacao: {
    id: "possui_iluminacao",
    label: "Possui iluminação?",
    type: "checkbox",
    defaultValue: false,
    xlsxKey: "possui_iluminacao",
    pptxKey: "possui_iluminacao",
  },
  iluminacao_fixada_alambrado: {
    id: "iluminacao_fixada_alambrado",
    label:
      "Iluminação será fixada em alambrado?",
    type: "checkbox",
    defaultValue: false,
    description:
      "Marque esta opção quando os projetores forem fixados em alambrado existente.",
    xlsxKey: "iluminacao_fixada_alambrado",
    pptxKey: "iluminacao_fixada_alambrado",
  },
  quantidade_postes_iluminacao: {
    id: "quantidade_postes_iluminacao",
    label: "Quantidade de postes",
    type: "number",
    unit: "un",
    xlsxKey: "quantidade_postes_iluminacao",
    pptxKey: "quantidade_postes_iluminacao",
  },
  altura_postes_iluminacao: {
    id: "altura_postes_iluminacao",
    label: "Altura dos postes",
    type: "number",
    unit: "m",
    xlsxKey: "altura_postes_iluminacao",
    pptxKey: "altura_postes_iluminacao",
  },
  quantidade_projetores: {
    id: "quantidade_projetores",
    label: "Quantidade de projetores/refletores",
    type: "number",
    unit: "un",
    xlsxKey: "quantidade_projetores",
    pptxKey: "quantidade_projetores",
  },
  potencia_projetores: {
    id: "potencia_projetores",
    label: "Potência dos projetores",
    type: "selectWithCustomOption",
    optionsKey: "potencia_projetores",
    customFieldId: "especificar_potencia_projetores",
    defaultValue: "200",
    xlsxKey: "potencia_projetores",
    pptxKey: "potencia_projetores",
  },
  especificar_potencia_projetores: {
    id: "especificar_potencia_projetores",
    label: "Especificar potência dos projetores",
    type: "text",
    placeholder: "Ex: 200 W",
    xlsxKey: "especificar_potencia_projetores",
    pptxKey: "especificar_potencia_projetores",
  },
  quantidade_cruzetas: {
    id: "quantidade_cruzetas",
    label: "Quantidade de cruzetas",
    type: "number",
    unit: "un",
    xlsxKey: "quantidade_cruzetas",
    pptxKey: "quantidade_cruzetas",
  },
  responsavel_ligacao_eletrica: {
    id: "responsavel_ligacao_eletrica",
    label: "Responsável pela ligação elétrica",
    type: "readonly",
    defaultValue: "cliente",
    readOnly: true,
    xlsxKey: "responsavel_ligacao_eletrica",
    pptxKey: "responsavel_ligacao_eletrica",
  },
  tipo_coligacao: {
    id: "tipo_coligacao",
    label: "Tipo de coligação",
    type: "select",
    optionsKey: "tipo_coligacao",
    xlsxKey: "tipo_coligacao",
    pptxKey: "tipo_coligacao",
  },
  possui_alambrado: {
    id: "possui_alambrado",
    label: "Possui alambrado?",
    type: "checkbox",
    defaultValue: false,
    xlsxKey: "possui_alambrado",
    pptxKey: "possui_alambrado",
  },
  sistema_alambrado: {
    id: "sistema_alambrado",
    label: "Sistema do alambrado",
    type: "select",
    optionsKey: "sistema_alambrado",
    xlsxKey: "sistema_alambrado",
    pptxKey: "sistema_alambrado",
  },
  comprimento_alambrado_laterais: {
    id: "comprimento_alambrado_laterais",
    label: "Comprimento",
    type: "number",
    unit: "m",
    xlsxKey: "comprimento_alambrado_laterais",
    pptxKey: "comprimento_alambrado_laterais",
  },
  altura_alambrado_laterais: {
    id: "altura_alambrado_laterais",
    label: "Altura",
    type: "number",
    unit: "m",
    xlsxKey: "altura_alambrado_laterais",
    pptxKey: "altura_alambrado_laterais",
  },
  espacamento_postes_tubos_laterais: {
    id: "espacamento_postes_tubos_laterais",
    label: "Espaçamento entre postes",
    type: "number",
    unit: "m",
    xlsxKey: "espacamento_postes_tubos_laterais",
    pptxKey: "espacamento_postes_tubos_laterais",
  },
  comprimento_alambrado_fundos: {
    id: "comprimento_alambrado_fundos",
    label: "Comprimento",
    type: "number",
    unit: "m",
    xlsxKey: "comprimento_alambrado_fundos",
    pptxKey: "comprimento_alambrado_fundos",
  },
  altura_alambrado_fundos: {
    id: "altura_alambrado_fundos",
    label: "Altura",
    type: "number",
    unit: "m",
    xlsxKey: "altura_alambrado_fundos",
    pptxKey: "altura_alambrado_fundos",
  },
  espacamento_postes_tubos_fundos: {
    id: "espacamento_postes_tubos_fundos",
    label: "Espaçamento entre postes",
    type: "number",
    unit: "m",
    xlsxKey: "espacamento_postes_tubos_fundos",
    pptxKey: "espacamento_postes_tubos_fundos",
  },
  galvanizacao: {
    id: "galvanizacao",
    label: "Galvanização",
    type: "selectWithCustomOption",
    optionsKey: "galvanizacao",
    customFieldId: "especificar_galvanizacao",
    xlsxKey: "galvanizacao",
    pptxKey: "galvanizacao",
  },
  especificar_galvanizacao: {
    id: "especificar_galvanizacao",
    label: "Especificar galvanização",
    type: "text",
    xlsxKey: "especificar_galvanizacao",
    pptxKey: "especificar_galvanizacao",
  },
  travamento: {
    id: "travamento",
    label: "Travamento",
    type: "multiselect",
    optionsKey: "travamento",
    xlsxKey: "travamento",
    pptxKey: "travamento",
  },
  quantidade_portoes: {
    id: "quantidade_portoes",
    label: "Quantidade de portões",
    type: "number",
    defaultValue: 0,
    xlsxKey: "quantidade_portoes",
    pptxKey: "quantidade_portoes",
  },
  altura_portoes: {
    id: "altura_portoes",
    label: "Altura dos portões",
    type: "number",
    unit: "m",
    defaultValue: 1.2,
    xlsxKey: "altura_portoes",
    pptxKey: "altura_portoes",
  },
  largura_portoes: {
    id: "largura_portoes",
    label: "Largura dos portões",
    type: "number",
    unit: "m",
    defaultValue: 2.2,
    xlsxKey: "largura_portoes",
    pptxKey: "largura_portoes",
  },
  possui_tela_superior: {
    id: "possui_tela_superior",
    label: "Possui tela superior?",
    type: "checkbox",
    defaultValue: false,
    xlsxKey: "possui_tela_superior",
    pptxKey: "possui_tela_superior",
  },
  cor_tela_superior: {
    id: "cor_tela_superior",
    label: "Cor da tela superior",
    type: "text",
    placeholder: "ex: branca",
    xlsxKey: "cor_tela_superior",
    pptxKey: "cor_tela_superior",
  },
  possui_tela_sombreamento: {
    id: "possui_tela_sombreamento",
    label: "Possui tela de sombreamento?",
    type: "checkbox",
    defaultValue: false,
    xlsxKey: "possui_tela_sombreamento",
    pptxKey: "possui_tela_sombreamento",
  },
  largura_sombreamento: {
    id: "largura_sombreamento",
    label: "Largura do sombreamento",
    type: "number",
    unit: "m",
    xlsxKey: "largura_sombreamento",
    pptxKey: "largura_sombreamento",
  },
  comprimento_sombreamento: {
    id: "comprimento_sombreamento",
    label: "Comprimento do sombreamento",
    type: "number",
    unit: "m",
    xlsxKey: "comprimento_sombreamento",
    pptxKey: "comprimento_sombreamento",
  },
  incluir_rede_tenis: {
    id: "incluir_rede_tenis",
    label: "Incluir rede de tênis?",
    type: "checkbox",
    defaultValue: false,
    xlsxKey: "incluir_rede_tenis",
    pptxKey: "incluir_rede_tenis",
  },
  possui_basquete_adulto: {
    id: "possui_basquete_adulto",
    label: "Basquete adulto",
    type: "checkbox",
    defaultValue: false,
    xlsxKey: "possui_basquete_adulto",
    pptxKey: "possui_basquete_adulto",
  },
  estrutura_basquete_adulto: {
    id: "estrutura_basquete_adulto",
    label: "Estrutura do basquete adulto",
    type: "select",
    optionsKey: "estrutura_basquete",
    xlsxKey: "estrutura_basquete_adulto",
    pptxKey: "estrutura_basquete_adulto",
  },
  possui_basquete_juvenil: {
    id: "possui_basquete_juvenil",
    label: "Basquete juvenil",
    type: "checkbox",
    defaultValue: false,
    xlsxKey: "possui_basquete_juvenil",
    pptxKey: "possui_basquete_juvenil",
  },
  possui_volei: {
    id: "possui_volei",
    label: "Vôlei",
    type: "checkbox",
    defaultValue: false,
    xlsxKey: "possui_volei",
    pptxKey: "possui_volei",
  },
  possui_futebol_futsal: {
    id: "possui_futebol_futsal",
    label: "Futebol/Futsal",
    type: "checkbox",
    defaultValue: false,
    xlsxKey: "possui_futebol_futsal",
    pptxKey: "possui_futebol_futsal",
  },
  tipo_futsal: {
    id: "tipo_futsal",
    label: "Tipo de Trave",
    type: "select",
    optionsKey: "tipo_futsal",
    xlsxKey: "tipo_futsal",
    pptxKey: "tipo_futsal",
  },
  possui_tenis: {
    id: "possui_tenis",
    label: "Tênis",
    type: "checkbox",
    defaultValue: false,
    xlsxKey: "possui_tenis",
    pptxKey: "possui_tenis",
  },
  possui_trave_3x2: {
    id: "possui_trave_3x2",
    label: "Trave 3x2",
    type: "checkbox",
    defaultValue: false,
    xlsxKey: "possui_trave_3x2",
    pptxKey: "possui_trave_3x2",
  },
  possui_trave_4x2: {
    id: "possui_trave_4x2",
    label: "Trave 4x2",
    type: "checkbox",
    defaultValue: false,
    xlsxKey: "possui_trave_4x2",
    pptxKey: "possui_trave_4x2",
  },
  possui_trave_5x2: {
    id: "possui_trave_5x2",
    label: "Trave 5x2",
    type: "checkbox",
    defaultValue: false,
    xlsxKey: "possui_trave_5x2",
    pptxKey: "possui_trave_5x2",
  },
  possui_trave_oficial: {
    id: "possui_trave_oficial",
    label: "Trave oficial 7,24 x 2,42",
    type: "checkbox",
    defaultValue: false,
    xlsxKey: "possui_trave_oficial",
    pptxKey: "possui_trave_oficial",
  },
  possui_rede_pickleball: {
    id: "possui_rede_pickleball",
    label: "Possui rede?",
    type: "checkbox",
    defaultValue: false,
    xlsxKey: "possui_rede_pickleball",
    pptxKey: "possui_rede_pickleball",
  },
  tipo_rede_pickleball: {
    id: "tipo_rede_pickleball",
    label: "Tipo da rede",
    type: "select",
    optionsKey: "tipo_rede_pickleball",
    xlsxKey: "tipo_rede_pickleball",
    pptxKey: "tipo_rede_pickleball",
  },
  tipo_estrutura_alambrado_padel: {
    id: "tipo_estrutura_alambrado_padel",
    label: "Tipo de estrutura do alambrado",
    type: "select",
    required: true,
    optionsKey: "tipo_estrutura_alambrado_padel",
    description: "Estrutura combina vidro e tela metálica.",
    xlsxKey: "tipo_estrutura_alambrado_padel",
    pptxKey: "tipo_estrutura_alambrado_padel",
  },
  largura_piso_liso: {
    id: "largura_piso_liso",
    label: "Largura do piso liso",
    type: "number",
    unit: "m",
    required: true,
    xlsxKey: "largura_piso_liso",
    pptxKey: "largura_piso_liso",
  },
  comprimento_piso_liso: {
    id: "comprimento_piso_liso",
    label: "Comprimento do piso liso",
    type: "number",
    unit: "m",
    required: true,
    xlsxKey: "comprimento_piso_liso",
    pptxKey: "comprimento_piso_liso",
  },
  area_piso_liso: {
    id: "area_piso_liso",
    label: "Área do piso liso",
    type: "number",
    unit: "m2",
    required: true,
    description: "Área preenchida manualmente.",
    xlsxKey: "area_piso_liso",
    pptxKey: "area_piso_liso",
  },
  largura_piso_derrapante: {
    id: "largura_piso_derrapante",
    label: "Largura do piso derrapante",
    type: "number",
    unit: "m",
    required: true,
    xlsxKey: "largura_piso_derrapante",
    pptxKey: "largura_piso_derrapante",
  },
  comprimento_piso_derrapante: {
    id: "comprimento_piso_derrapante",
    label: "Comprimento do piso derrapante",
    type: "number",
    unit: "m",
    required: true,
    xlsxKey: "comprimento_piso_derrapante",
    pptxKey: "comprimento_piso_derrapante",
  },
  area_piso_derrapante: {
    id: "area_piso_derrapante",
    label: "Área do piso derrapante",
    type: "number",
    unit: "m2",
    required: true,
    description: "Área preenchida manualmente.",
    xlsxKey: "area_piso_derrapante",
    pptxKey: "area_piso_derrapante",
  },
  possui_multilayer_garagem_epoxi: {
    id: "possui_multilayer_garagem_epoxi",
    label: "Multilayer",
    type: "checkbox",
    defaultValue: false,
    xlsxKey: "possui_multilayer_garagem_epoxi",
    pptxKey: "possui_multilayer_garagem_epoxi",
  },
  metro_linear_faixa: {
    id: "metro_linear_faixa",
    label: "Metro linear faixa",
    type: "number",
    unit: "m",
    required: true,
    description: "Determina a altura da faixa.",
    xlsxKey: "metro_linear_faixa",
    pptxKey: "metro_linear_faixa",
  },
  possui_vagas_carro: {
    id: "possui_vagas_carro",
    label: "Vagas de carro",
    type: "checkbox",
    defaultValue: false,
    xlsxKey: "possui_vagas_carro",
    pptxKey: "possui_vagas_carro",
  },
  quantidade_vagas_carro: {
    id: "quantidade_vagas_carro",
    label: "Quantidade de vagas de carro",
    type: "number",
    unit: "un",
    required: true,
    xlsxKey: "quantidade_vagas_carro",
    pptxKey: "quantidade_vagas_carro",
  },
  largura_vaga_carro: {
    id: "largura_vaga_carro",
    label: "Largura da vaga de carro",
    type: "number",
    unit: "m",
    required: true,
    xlsxKey: "largura_vaga_carro",
    pptxKey: "largura_vaga_carro",
  },
  comprimento_vaga_carro: {
    id: "comprimento_vaga_carro",
    label: "Comprimento da vaga de carro",
    type: "number",
    unit: "m",
    required: true,
    xlsxKey: "comprimento_vaga_carro",
    pptxKey: "comprimento_vaga_carro",
  },
  possui_vagas_moto: {
    id: "possui_vagas_moto",
    label: "Vagas de moto",
    type: "checkbox",
    defaultValue: false,
    xlsxKey: "possui_vagas_moto",
    pptxKey: "possui_vagas_moto",
  },
  quantidade_vagas_moto: {
    id: "quantidade_vagas_moto",
    label: "Quantidade de vagas de moto",
    type: "number",
    unit: "un",
    required: true,
    xlsxKey: "quantidade_vagas_moto",
    pptxKey: "quantidade_vagas_moto",
  },
  largura_vaga_moto: {
    id: "largura_vaga_moto",
    label: "Largura da vaga de moto",
    type: "number",
    unit: "m",
    required: true,
    xlsxKey: "largura_vaga_moto",
    pptxKey: "largura_vaga_moto",
  },
  comprimento_vaga_moto: {
    id: "comprimento_vaga_moto",
    label: "Comprimento da vaga de moto",
    type: "number",
    unit: "m",
    required: true,
    xlsxKey: "comprimento_vaga_moto",
    pptxKey: "comprimento_vaga_moto",
  },
  possui_vagas_bicicleta: {
    id: "possui_vagas_bicicleta",
    label: "Vagas de bicicleta",
    type: "checkbox",
    defaultValue: false,
    xlsxKey: "possui_vagas_bicicleta",
    pptxKey: "possui_vagas_bicicleta",
  },
  quantidade_vagas_bicicleta: {
    id: "quantidade_vagas_bicicleta",
    label: "Quantidade de vagas de bicicleta",
    type: "number",
    unit: "un",
    required: true,
    xlsxKey: "quantidade_vagas_bicicleta",
    pptxKey: "quantidade_vagas_bicicleta",
  },
  largura_vaga_bicicleta: {
    id: "largura_vaga_bicicleta",
    label: "Largura da vaga de bicicleta",
    type: "number",
    unit: "m",
    required: true,
    xlsxKey: "largura_vaga_bicicleta",
    pptxKey: "largura_vaga_bicicleta",
  },
  comprimento_vaga_bicicleta: {
    id: "comprimento_vaga_bicicleta",
    label: "Comprimento da vaga de bicicleta",
    type: "number",
    unit: "m",
    required: true,
    xlsxKey: "comprimento_vaga_bicicleta",
    pptxKey: "comprimento_vaga_bicicleta",
  },
  possui_vagas_pne: {
    id: "possui_vagas_pne",
    label: "Vagas PNE",
    type: "checkbox",
    defaultValue: false,
    xlsxKey: "possui_vagas_pne",
    pptxKey: "possui_vagas_pne",
  },
  quantidade_vagas_pne: {
    id: "quantidade_vagas_pne",
    label: "Quantidade de vagas PNE",
    type: "number",
    unit: "un",
    required: true,
    xlsxKey: "quantidade_vagas_pne",
    pptxKey: "quantidade_vagas_pne",
  },
  largura_vaga_pne: {
    id: "largura_vaga_pne",
    label: "Largura da vaga PNE",
    type: "number",
    unit: "m",
    required: true,
    xlsxKey: "largura_vaga_pne",
    pptxKey: "largura_vaga_pne",
  },
  comprimento_vaga_pne: {
    id: "comprimento_vaga_pne",
    label: "Comprimento da vaga PNE",
    type: "number",
    unit: "m",
    required: true,
    xlsxKey: "comprimento_vaga_pne",
    pptxKey: "comprimento_vaga_pne",
  },
  observacoes: {
    id: "observacoes",
    label: "Observações",
    type: "textarea",
    placeholder: "ex: Quadra de Tênis PA será coligada com a Quadra de Tênis Saibro",
    rows: 5,
    xlsxKey: "observacoes",
    pptxKey: "observacoes",
  },
};

export { fieldRegistry };
